
development:
  adapter: sqlite3
  database: ./db/expensives.db
  
production:
  encoding: unicode
  adapter: postgresql
  username: jetjyotrfa
  port: 5432
  host: ec2-184-72-250-169.compute-1.amazonaws.com
  database: jetjyotrfa
  password: f5lxx1zz5pnorynqglhzmsp34
